// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using OpenAI.Chat;

namespace OpenAI.Chat
{
    [Experimental("OPENAI001")]
    public partial class CreateChatCompletionResponseChoice
    {
        private protected IDictionary<string, BinaryData> _additionalBinaryDataProperties;

        internal CreateChatCompletionResponseChoice(ChatFinishReason finishReason, int index, InternalChatCompletionResponseMessage message, InternalCreateChatCompletionResponseChoiceLogprobs logprobs)
        {
            FinishReason = finishReason;
            Index = index;
            Message = message;
            Logprobs = logprobs;
        }

        internal CreateChatCompletionResponseChoice(ChatFinishReason finishReason, int index, InternalChatCompletionResponseMessage message, InternalCreateChatCompletionResponseChoiceLogprobs logprobs, IDictionary<string, BinaryData> additionalBinaryDataProperties)
        {
            FinishReason = finishReason;
            Index = index;
            Message = message;
            Logprobs = logprobs;
            _additionalBinaryDataProperties = additionalBinaryDataProperties;
        }

        public ChatFinishReason FinishReason { get; }

        public int Index { get; }

        internal InternalChatCompletionResponseMessage Message { get; }

        internal InternalCreateChatCompletionResponseChoiceLogprobs Logprobs { get; }

        internal IDictionary<string, BinaryData> SerializedAdditionalRawData
        {
            get => _additionalBinaryDataProperties;
            set => _additionalBinaryDataProperties = value;
        }
    }
}
