// <auto-generated/>

#nullable disable

using System.ClientModel.Primitives;
using OpenAI.Assistants;
using OpenAI.Audio;
using OpenAI.Batch;
using OpenAI.Chat;
using OpenAI.Containers;
using OpenAI.Embeddings;
using OpenAI.Evals;
using OpenAI.Files;
using OpenAI.FineTuning;
using OpenAI.Graders;
using OpenAI.Images;
using OpenAI.Internal;
using OpenAI.LegacyCompletions;
using OpenAI.Models;
using OpenAI.Moderations;
using OpenAI.Realtime;
using OpenAI.Responses;
using OpenAI.VectorStores;

namespace OpenAI
{
    // [ModelReaderWriterBuildable(typeof(CreateChatCompletionRequestBody))]
    public partial class OpenAIContext : ModelReaderWriterContext
    {
    }
}
