// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using OpenAI.Chat;

namespace OpenAI.Chat
{
    [Experimental("OPENAI001")]
    public partial class ChatCompletionRequestUserMessage : ChatMessage
    {
        public ChatCompletionRequestUserMessage() : this(ChatMessageRole.User, null, null, null)
        {
        }

        internal ChatCompletionRequestUserMessage(ChatMessageRole role, ChatMessageContent content, IDictionary<string, BinaryData> additionalBinaryDataProperties, string name) : base(role, content, additionalBinaryDataProperties)
        {
            Name = name;
        }

        public string Name { get; set; }
    }
}
