// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using OpenAI.Chat;

namespace OpenAI.Chat
{
    [Experimental("OPENAI001")]
    public partial class ChatCompletionRequestToolMessage : ChatMessage
    {
        public ChatCompletionRequestToolMessage(string toolCallId) : base(ChatMessageRole.Tool)
        {
            Argument.AssertNotNull(toolCallId, nameof(toolCallId));

            ToolCallId = toolCallId;
        }

        internal ChatCompletionRequestToolMessage(ChatMessageRole role, ChatMessageContent content, IDictionary<string, BinaryData> additionalBinaryDataProperties, string toolCallId) : base(role, content, additionalBinaryDataProperties)
        {
            ToolCallId = toolCallId;
        }

        public string ToolCallId { get; }
    }
}
