// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using OpenAI.Moderations;

namespace OpenAI
{
    [Experimental("OPENAI001")]
    public partial class CreateModerationResponse
    {
        private protected IDictionary<string, BinaryData> _additionalBinaryDataProperties;

        internal CreateModerationResponse(string id, string model, IEnumerable<CreateModerationResponseResult> results)
        {
            Id = id;
            Model = model;
            Results = results.ToList();
        }

        internal CreateModerationResponse(string id, string model, IList<CreateModerationResponseResult> results, IDictionary<string, BinaryData> additionalBinaryDataProperties)
        {
            // Plugin customization: ensure initialization of collections
            Id = id;
            Model = model;
            Results = results ?? new ChangeTrackingList<CreateModerationResponseResult>();
            _additionalBinaryDataProperties = additionalBinaryDataProperties;
        }

        public string Id { get; }

        public string Model { get; }

        public IList<CreateModerationResponseResult> Results { get; }

        internal IDictionary<string, BinaryData> SerializedAdditionalRawData
        {
            get => _additionalBinaryDataProperties;
            set => _additionalBinaryDataProperties = value;
        }
    }
}
