// <auto-generated/>

#nullable disable

using System;
using System.ClientModel;
using System.ClientModel.Primitives;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using OpenAI;

namespace OpenAI.Moderations
{
    public partial class ModerationResultResponse : IJsonModel<ModerationResultResponse>
    {
        public ModerationResultResponse()
        {
        }

        void IJsonModel<ModerationResultResponse>.Write(Utf8JsonWriter writer, ModelReaderWriterOptions options)
        {
            writer.WriteStartObject();
            JsonModelWriteCore(writer, options);
            writer.WriteEndObject();
        }

        [Experimental("OPENAI001")]
        protected virtual void JsonModelWriteCore(Utf8JsonWriter writer, ModelReaderWriterOptions options)
        {
            string format = options.Format == "W" ? ((IPersistableModel<ModerationResult>)this).GetFormatFromOptions(options) : options.Format;
            if (format != "J")
            {
                throw new FormatException($"The model {nameof(ModerationResult)} does not support writing '{format}' format.");
            }
            if (_additionalBinaryDataProperties?.ContainsKey("flagged") != true)
            {
                writer.WritePropertyName("flagged"u8);
                writer.WriteBooleanValue(Flagged);
            }
            if (_additionalBinaryDataProperties?.ContainsKey("categories") != true)
            {
                writer.WritePropertyName("categories"u8);
                writer.WriteObjectValue(Categories, options);
            }
            if (_additionalBinaryDataProperties?.ContainsKey("category_scores") != true)
            {
                writer.WritePropertyName("category_scores"u8);
                writer.WriteObjectValue(CategoryScores, options);
            }
            if (_additionalBinaryDataProperties?.ContainsKey("category_applied_input_types") != true)
            {
                writer.WritePropertyName("category_applied_input_types"u8);
                writer.WriteObjectValue(CategoryAppliedInputTypes, options);
            }
            // Plugin customization: remove options.Format != "W" check
            if (_additionalBinaryDataProperties != null)
            {
                foreach (var item in _additionalBinaryDataProperties)
                {
                    if (ModelSerializationExtensions.IsSentinelValue(item.Value))
                    {
                        continue;
                    }
                    writer.WritePropertyName(item.Key);
#if NET6_0_OR_GREATER
                    writer.WriteRawValue(item.Value);
#else
                    using (JsonDocument document = JsonDocument.Parse(item.Value))
                    {
                        JsonSerializer.Serialize(writer, document.RootElement);
                    }
#endif
                }
            }
        }

        ModerationResultResponse IJsonModel<ModerationResultResponse>.Create(ref Utf8JsonReader reader, ModelReaderWriterOptions options) => JsonModelCreateCore(ref reader, options);

        [Experimental("OPENAI001")]
        protected virtual ModerationResultResponse JsonModelCreateCore(ref Utf8JsonReader reader, ModelReaderWriterOptions options)
        {
            string format = options.Format == "W" ? ((IPersistableModel<ModerationResult>)this).GetFormatFromOptions(options) : options.Format;
            if (format != "J")
            {
                throw new FormatException($"The model {nameof(ModerationResult)} does not support reading '{format}' format.");
            }
            using JsonDocument document = JsonDocument.ParseValue(ref reader);
            return DeserializeModerationResult(document.RootElement, options);
        }

        internal static ModerationResultResponse DeserializeModerationResult(JsonElement element, ModelReaderWriterOptions options)
        {
            if (element.ValueKind == JsonValueKind.Null)
            {
                return null;
            }
            bool flagged = default;
            ModerationCategories categories = default;
            ModerationCategoryScores categoryScores = default;
            CreateModerationResponseResultCategoryAppliedInputTypes categoryAppliedInputTypes = default;
            IDictionary<string, BinaryData> additionalBinaryDataProperties = new ChangeTrackingDictionary<string, BinaryData>();
            foreach (var prop in element.EnumerateObject())
            {
                if (prop.NameEquals("flagged"u8))
                {
                    flagged = prop.Value.GetBoolean();
                    continue;
                }
                if (prop.NameEquals("categories"u8))
                {
                    categories = ModerationCategories.DeserializeModerationCategories(prop.Value, options);
                    continue;
                }
                if (prop.NameEquals("category_scores"u8))
                {
                    categoryScores = ModerationCategoryScores.DeserializeModerationCategoryScores(prop.Value, options);
                    continue;
                }
                if (prop.NameEquals("category_applied_input_types"u8))
                {
                    categoryAppliedInputTypes = CreateModerationResponseResultCategoryAppliedInputTypes.DeserializeCreateModerationResponseResultCategoryAppliedInputTypes(prop.Value, options);
                    continue;
                }
                // Plugin customization: remove options.Format != "W" check
                additionalBinaryDataProperties.Add(prop.Name, BinaryData.FromString(prop.Value.GetRawText()));
            }
            return new ModerationResultResponse(flagged, categories, categoryScores, categoryAppliedInputTypes, additionalBinaryDataProperties);
        }

        BinaryData IPersistableModel<ModerationResultResponse>.Write(ModelReaderWriterOptions options) => PersistableModelWriteCore(options);

        [Experimental("OPENAI001")]
        protected virtual BinaryData PersistableModelWriteCore(ModelReaderWriterOptions options)
        {
            string format = options.Format == "W" ? ((IPersistableModel<ModerationResult>)this).GetFormatFromOptions(options) : options.Format;
            switch (format)
            {
                case "J":
                    return ModelReaderWriter.Write(this, options, OpenAIContext.Default);
                default:
                    throw new FormatException($"The model {nameof(ModerationResult)} does not support writing '{options.Format}' format.");
            }
        }

        ModerationResultResponse IPersistableModel<ModerationResultResponse>.Create(BinaryData data, ModelReaderWriterOptions options) => PersistableModelCreateCore(data, options);

        [Experimental("OPENAI001")]
        protected virtual ModerationResultResponse PersistableModelCreateCore(BinaryData data, ModelReaderWriterOptions options)
        {
            string format = options.Format == "W" ? ((IPersistableModel<ModerationResultResponse>)this).GetFormatFromOptions(options) : options.Format;
            switch (format)
            {
                case "J":
                    using (JsonDocument document = JsonDocument.Parse(data))
                    {
                        return DeserializeModerationResult(document.RootElement, options);
                    }
                default:
                    throw new FormatException($"The model {nameof(ModerationResult)} does not support reading '{options.Format}' format.");
            }
        }

        string IPersistableModel<ModerationResultResponse>.GetFormatFromOptions(ModelReaderWriterOptions options) => "J";

        public static implicit operator ModerationResultResponse(ClientResult result)
        {
            using PipelineResponse response = result.GetRawResponse();
            using JsonDocument document = JsonDocument.Parse(response.Content);
            return DeserializeModerationResult(document.RootElement, ModelSerializationExtensions.WireOptions);
        }
    }
}
