// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;

namespace OpenAI
{
    [Experimental("OPENAI001")]
    public partial class ResponseFormatJsonObject : ResponseFormat
    {
        public ResponseFormatJsonObject() : this(ResponseFormatType.JsonObject, null)
        {
        }

        internal ResponseFormatJsonObject(ResponseFormatType kind, IDictionary<string, BinaryData> additionalBinaryDataProperties) : base(kind, additionalBinaryDataProperties)
        {
        }
    }
}
