// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using OpenAI.Internal;

namespace OpenAI
{
    [Experimental("OPENAI001")]
    public partial class ResponseFormatJsonSchema : ResponseFormat
    {
        internal ResponseFormatJsonSchema(InternalResponseFormatJsonSchemaJsonSchema jsonSchema) : base(ResponseFormatType.JsonSchema)
        {
            Argument.AssertNotNull(jsonSchema, nameof(jsonSchema));

            JsonSchema = jsonSchema;
        }

        internal ResponseFormatJsonSchema(ResponseFormatType kind, IDictionary<string, BinaryData> additionalBinaryDataProperties, InternalResponseFormatJsonSchemaJsonSchema jsonSchema) : base(kind, additionalBinaryDataProperties)
        {
            JsonSchema = jsonSchema;
        }

        internal InternalResponseFormatJsonSchemaJsonSchema JsonSchema { get; set; }
    }
}
