// <auto-generated/>

#nullable disable

using System;
using System.ClientModel.Primitives;
using System.Collections.Generic;
using System.Text.Json;

namespace OpenAI
{
    public partial class ResponseFormatText : ResponseFormat, IJsonModel<ResponseFormatText>
    {
        void IJsonModel<ResponseFormatText>.Write(Utf8JsonWriter writer, ModelReaderWriterOptions options)
        {
            writer.WriteStartObject();
            JsonModelWriteCore(writer, options);
            writer.WriteEndObject();
        }

        protected override void JsonModelWriteCore(Utf8JsonWriter writer, ModelReaderWriterOptions options)
        {
            string format = options.Format == "W" ? ((IPersistableModel<ResponseFormatText>)this).GetFormatFromOptions(options) : options.Format;
            if (format != "J")
            {
                throw new FormatException($"The model {nameof(ResponseFormatText)} does not support writing '{format}' format.");
            }
            base.JsonModelWriteCore(writer, options);
        }

        ResponseFormatText IJsonModel<ResponseFormatText>.Create(ref Utf8JsonReader reader, ModelReaderWriterOptions options) => (ResponseFormatText)JsonModelCreateCore(ref reader, options);

        protected override ResponseFormat JsonModelCreateCore(ref Utf8JsonReader reader, ModelReaderWriterOptions options)
        {
            string format = options.Format == "W" ? ((IPersistableModel<ResponseFormatText>)this).GetFormatFromOptions(options) : options.Format;
            if (format != "J")
            {
                throw new FormatException($"The model {nameof(ResponseFormatText)} does not support reading '{format}' format.");
            }
            using JsonDocument document = JsonDocument.ParseValue(ref reader);
            return DeserializeResponseFormatText(document.RootElement, options);
        }

        internal static ResponseFormatText DeserializeResponseFormatText(JsonElement element, ModelReaderWriterOptions options)
        {
            if (element.ValueKind == JsonValueKind.Null)
            {
                return null;
            }
            ResponseFormatType kind = default;
            IDictionary<string, BinaryData> additionalBinaryDataProperties = new ChangeTrackingDictionary<string, BinaryData>();
            foreach (var prop in element.EnumerateObject())
            {
                if (prop.NameEquals("type"u8))
                {
                    kind = prop.Value.GetString().ToResponseFormatType();
                    continue;
                }
                // Plugin customization: remove options.Format != "W" check
                additionalBinaryDataProperties.Add(prop.Name, BinaryData.FromString(prop.Value.GetRawText()));
            }
            return new ResponseFormatText(kind, additionalBinaryDataProperties);
        }

        BinaryData IPersistableModel<ResponseFormatText>.Write(ModelReaderWriterOptions options) => PersistableModelWriteCore(options);

        protected override BinaryData PersistableModelWriteCore(ModelReaderWriterOptions options)
        {
            string format = options.Format == "W" ? ((IPersistableModel<ResponseFormatText>)this).GetFormatFromOptions(options) : options.Format;
            switch (format)
            {
                case "J":
                    return ModelReaderWriter.Write(this, options, OpenAIContext.Default);
                default:
                    throw new FormatException($"The model {nameof(ResponseFormatText)} does not support writing '{options.Format}' format.");
            }
        }

        ResponseFormatText IPersistableModel<ResponseFormatText>.Create(BinaryData data, ModelReaderWriterOptions options) => (ResponseFormatText)PersistableModelCreateCore(data, options);

        protected override ResponseFormat PersistableModelCreateCore(BinaryData data, ModelReaderWriterOptions options)
        {
            string format = options.Format == "W" ? ((IPersistableModel<ResponseFormatText>)this).GetFormatFromOptions(options) : options.Format;
            switch (format)
            {
                case "J":
                    using (JsonDocument document = JsonDocument.Parse(data))
                    {
                        return DeserializeResponseFormatText(document.RootElement, options);
                    }
                default:
                    throw new FormatException($"The model {nameof(ResponseFormatText)} does not support reading '{options.Format}' format.");
            }
        }

        string IPersistableModel<ResponseFormatText>.GetFormatFromOptions(ModelReaderWriterOptions options) => "J";
    }
}
