// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;

namespace OpenAI
{
    [Experimental("OPENAI001")]
    public partial class ResponseFormatText : ResponseFormat
    {
        public ResponseFormatText() : this(ResponseFormatType.Text, null)
        {
        }

        internal ResponseFormatText(ResponseFormatType kind, IDictionary<string, BinaryData> additionalBinaryDataProperties) : base(kind, additionalBinaryDataProperties)
        {
        }
    }
}
