// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;

namespace OpenAI
{
    internal partial class UnknownResponseFormat : ResponseFormat
    {
        internal UnknownResponseFormat(ResponseFormatType kind, IDictionary<string, BinaryData> additionalBinaryDataProperties) : base(kind, additionalBinaryDataProperties)
        {
        }
    }
}
